### ISSUE TITLE
I found thing goes wrong after update the delete animation

### ISSUE THREAD

**Issue by MrBoog** [theswiftdev/self-sizing-cells#1]
Hey, 
I added this method in `extension CollectionViewController`, looks like self-sizing just doesn't work when we wanna delete items. (The delete animation becomes really weird)

here is the code

```
    override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        self.collectionView?.performBatchUpdates({
            self.dataSource.remove(at: indexPath.item)
            self.collectionView?.deleteItems(at: [indexPath])
        }, completion: { (finished) in
        })
    }

```

any idea?

**Comment by MrBoog** [comment]
Is it a bug of collectionView?

here are some similar problems:
https://github.com/lionheart/openradar-mirror/issues/18964
https://stackoverflow.com/questions/38761231/uicollectionview-with-self-sizing-cells-uses-estimateditemsize-for-delete-animat

**Comment by tib** [comment]
Self-sizing cells are buggy in general, but I have to check on this specific issue, give me a few days... ;)

**Comment by tib** [comment]
@MrBoog i've tried your method and it worked for me without problems, could you please provide more details about this issue?

**Comment by MrBoog** [comment]
Hmmm, I'm not sure. Actually, I guess it's not a big deal, just animation is not smooth enough.
I fixed this by using calculate the cell height manually,

```
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let width = bounds.width
        let height = heightForItem(at: indexPath, forWidth: width)
        return CGSize(width: width, height: height)
    }
```

or another solution is to override `invalidationContext(forPreferredLayoutAttributes:withOriginalAttributes)` (I've tried, also could work)

**Comment by tib** [comment]
@MrBoog to be honest, I usually go with my [CoreKit](https://github.com/corekit/corekit) framework for collection views. I don't use the self sizing feature at all, because of it's bugs. Feel free to try it. ;) If you're okay with that I'm going to close this issue.

**Comment by MrBoog** [comment]
Yeah, sure of course, thanks
